require('dotenv').config({ path: require('path').join(__dirname, '.env') });
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

const products = [
  { sku: 'V628#A', brand: 'Under Armour', category: ['tops', 'ua'], name: 'Complet habit avec culotte Under Armour - disponible en 3 couleurs', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['#ff4d4d', '#888', '#fff', '#111'], fabric: 'Polyester Dri-FIT', desc: 'double construction en tissu — panneau supérieur en mesh pour la respirabilité. Logo under armour. Parfait pour la salle, la course et le quotidien.', icon: '👕', badge: 'BESTSELLER', images: ['https://i.ibb.co/whY92KLn/1u-c-b.jpg'] },
  { sku: 'PL6664#', brand: 'Under Armour', category: ['tops', 'ua'], name: 'Complet habit avec culotte Under Armour', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['#b8d4e8'], fabric: 'Polyester Dri-FIT', desc: 'double construction en tissu — panneau supérieur en mesh pour la respirabilité. Logo under armour. Parfait pour la salle, la course et le quotidien.', icon: '👔', badge: null, images: ['https://i.ibb.co/p6VjGZLv/2.jpg'] },
  { sku: 'PL6643#', brand: 'Adidas', category: ['tops', 'adidas'], name: 'Complet habit avec culotte Adidas', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['#1a2a4a'], fabric: 'Polyester Dri-FIT', desc: 'double construction en tissu — panneau supérieur en mesh pour la respirabilité. Logo adidas. Parfait pour la salle, la course et le quotidien', icon: '👔', badge: null, images: ['https://i.ibb.co/DfZFbmNN/4.jpg'] },
  { sku: 'PL6697#', brand: 'Adidas', category: ['tops', 'adidas'], name: 'Adidas Polo Classique – 4 Coloris', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#fff', '#888', '#111', '#7dd1d1'], fabric: 'Performance Knit', desc: 'Polo coupe épurée disponible en Blanc, Gris, Noir et Bleu ciel. Patch Adidas en bas. Coupe slim athlétique. Parfait pour le sport, les loisirs ou le quotidien.', icon: '👔', badge: null, images: ['https://i.ibb.co/HDypynTh/5.jpg'] },
  { sku: 'PL6699#', brand: 'Nike', category: ['tops', 'nike'], name: 'Nike Just Do It Polo – 4 Coloris', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#fff', '#c8aa7a', '#111', '#5a1a2a'], fabric: 'Performance Mesh', desc: 'Disponible en Blanc, Kaki, Noir et Bordeaux. Branding Nike "Just Do It" en bas. Polo premium coupe moderne. Idéal pour le sport and le lifestyle.', icon: '👔', badge: null, images: ['https://i.ibb.co/FLsM69L0/6.jpg'] },
  { sku: 'PL6700#', brand: 'Under Armour', category: ['tops', 'ua'], name: 'Under Armour HeatGear Polo – 4 Coloris', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#fff', '#6a7fa0', '#111', '#c47a60'], fabric: 'HeatGear Fabric', desc: 'Disponible en Blanc, Bleu acier, Noir et Terracotta. Technologie HeatGear évacuant la transpiration. Coupe ajustée pour performance et style maximum.', icon: '👔', badge: 'NEW', images: ['https://i.ibb.co/9ksYL010/7.jpg'] },
  { sku: 'HD9016#', brand: 'Nike', category: ['pants', 'nike'], name: 'Nike Just Do It Pantalon Training – 4 Coloris', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#222', '#2a3d5a', '#1a2a4a', '#4a9090'], fabric: 'Quick-Dry Woven', desc: 'Pantalon training slim avec cordon à la taille. Disponible en Anthracite, Bleu Teal, Marine et Turquoise. Swoosh Nike sur la cuisse. Poche zippée latérale.', icon: '👖', badge: null, images: ['https://i.ibb.co/LXqXQPWZ/8.jpg'] },
  { sku: 'HD9014#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Adidas Pantalon 3 Bandes Classique', price: 14000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#1a2a4a'], fabric: 'Polyester', desc: "Jogging marine classique Adidas avec les 3 bandes blanches iconiques. Ceinture élastique avec cordon. Poches latérales. Coupe décontractée parfaite pour l'entraînement.", icon: '👖', badge: 'CLASSIC', images: ['https://i.ibb.co/mFzR9SsF/9.jpg'] },
  { sku: 'HD9033#', brand: 'Under Armour', category: ['pants', 'ua'], name: 'Under Armour Jogger Slim – 4 Coloris', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#1a2a4a', '#444', '#111', '#1a3a4a'], fabric: 'UA Stretch Woven', desc: 'Jogger slim effilé disponible en Marine, Gris foncé, Noir et Teal foncé. Logo Under Armour sur la cuisse. Ceinture élastique. Poches latérales.', icon: '👖', badge: null, images: ['https://i.ibb.co/TBQLr9Td/10.jpg'] },
  { sku: 'HD9034#', brand: 'Nike', category: ['pants', 'nike'], name: 'Nike Pantalon Noir Swoosh Or', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111'], fabric: 'Stretch Woven', desc: 'Pantalon performance tout noir with un Swoosh Nike or et blanc sur la jambe. Ceinture à cordon, coupe effilée. Une pièce bold pour le streetwear.', icon: '👖', badge: 'HOT', images: ['https://i.ibb.co/7xyQLn1G/12.jpg'] },
  { sku: '757#557# U', brand: 'Under Armour', category: ['sets', 'ua'], name: 'UA Ensemble Training Imprimé – 4 Coloris', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#f0f0f0', '#666', '#2a2a3a'], fabric: 'Nylon + Spandex', desc: 'Ensemble t-shirt + short assorti. Imprimé all-over avec logo UA. Disponible en Noir, Blanc, Gris and Marine foncé. Mélange nylon-spandex léger.', icon: '🩱', badge: 'SET', images: ['https://i.ibb.co/chMhyQjx/14.jpg'] },
  { sku: 'SC1012#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 12', price: 14000, sizes: ['M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/chMhyQjx/14.jpg'] },
  { sku: 'SC1013#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 13', price: 14000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/5gsWnPbP/15.jpg'] },
  { sku: 'SC1014#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 14', price: 14000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/TMbZC3Pf/16.jpg'] },
  { sku: 'SC1015#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 15', price: 14000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: 'NEW', images: ['https://i.ibb.co/8nnTRv6r/18.jpg'] },
  { sku: 'SC1016#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 16', price: 14000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/PZSNHVv1/19.jpg'] },
  { sku: 'SC1017#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 17', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/213JkP9h/20.jpg'] },
  { sku: 'SC1018#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 18', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/HDypynTh/5.jpg'] },
  { sku: 'SC1019#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 19', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/FLsM69L0/6.jpg'] },
  { sku: 'SC1020#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 20', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/jZMMWw8R/25.jpg'] },
  { sku: 'SC1021#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 21', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/fdGzvW9P/26.jpg'] },
  { sku: 'SC1022#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 22', price: 14000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/BHvFVNgw/27.jpg'] },
  { sku: 'SC1023#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 23', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/rfbtYJJ0/28.jpg'] },
  { sku: 'SC1024#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 24', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/qM0H0dZK/29.jpg'] },
  { sku: 'SC1025#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 25', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/TMkFfCFS/30.jpg'] },
  { sku: 'SC1026#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 26', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/LhHKNBd3/31.jpg'] },
  { sku: 'SC1027#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 27', price: 18000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/cMXcbwx/32.jpg'] },
  { sku: 'SC1028#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 28', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/SDj3KQPS/33.jpg'] },
  { sku: 'SC1029#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 29', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/WWpMJhN3/34.jpg'] },
  { sku: 'SC1030#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 30', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/WWpMJhN3/34.jpg'] },
  { sku: 'SC1031#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 31', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/cSkt7wFy/36.jpg'] },
  { sku: 'SC1032#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 32', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/vxVT1qkv/37.jpg'] },
  { sku: 'SC1033#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 33', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/PvkyLLs0/38.jpg'] },
  { sku: 'SC1034#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 34', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/mrF24jfS/39.jpg'] },
  { sku: 'SC1035#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 35', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/HTH1Nkv3/40.jpg'] },
  { sku: 'SC1036#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 36', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/205T2cSR/41.jpg'] },
  { sku: 'SC1037#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 37', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/bffh6NC/42.jpg'] },
  { sku: 'SC1038#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 38', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/4g13V3d1/43.jpg'] },
  { sku: 'SC1039#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 39', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/WdpWF7y/44.jpg'] },
  { sku: 'SC1040#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 40', price: 18000, sizes: ['L', 'XL', '2XL', '3XL', '4XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/3YWhwwjG/45.jpg'] },
  { sku: 'SC1041#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 41', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/5XGXc15V/46.jpg'] },
  { sku: 'SC1042#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 42', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/tTSmR0WV/47.jpg'] },
  { sku: 'SC1043#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 43', price: 18000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/zHhjW5VH/48.jpg'] },
  { sku: 'SC1044#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 44', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/v6HMwMc4/49.jpg'] },
  { sku: 'SC1045#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 45', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: 'NEW', images: ['https://i.ibb.co/1GHgZ47L/50.jpg'] },
  { sku: 'SC1046#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 46', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/B5Jt3ZPv/51.jpg'] },
  { sku: 'SC1047#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 47', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/hJLNmzy2/52.jpg'] },
  { sku: 'SC1048#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 48', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/bjFHHSbf/53.jpg'] },
  { sku: 'SC1049#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 49', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/pvv6PVJ6/54.jpg'] },
  { sku: 'SC1050#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 50', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/gbZG9sPN/55.jpg'] },
  { sku: 'SC1051#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 51', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/fdxGGqQS/56.jpg'] },
  { sku: 'SC1052#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 52', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/tTSmR0WV/47.jpg'] },
  { sku: 'SC1053#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 53', price: 12000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/nsgjvmhm/58.jpg'] },
  { sku: 'SC1054#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 54', price: 12000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/C5w1Cs9N/59.jpg'] },
  { sku: 'SC1055#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 55', price: 12000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/RW41FGq/60.jpg'] },
  { sku: 'SC1056#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 56', price: 12000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/Tx9K1Gs8/61.jpg'] },
  { sku: 'SC1057#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 57', price: 12000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/fYX0CJGJ/62.jpg'] },
  { sku: 'SC1058#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 58', price: 12000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/dsvKKSj5/63.jpg'] },
  { sku: 'SC1059#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 59', price: 5000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/ymZVXPF0/64.jpg'] },
  { sku: 'SC1060#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 60', price: 5000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: 'NEW', images: ['https://i.ibb.co/KzhkcGC8/65.jpg'] },
  { sku: 'SC1061#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 61', price: 5000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/jPCGLSr8/66.jpg'] },
  { sku: 'SC1062#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 62', price: 18000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/27SvvYYj/67.jpg'] },
  { sku: 'SC1063#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 63', price: 5000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/4wYncKJz/68.jpg'] },
  { sku: 'SC1064#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 64', price: 18000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/nsZF9YCH/69.jpg'] },
  { sku: 'SC1065#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 65', price: 18000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/qMH7z8cW/70.jpg'] },
  { sku: 'SC1066#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 66', price: 8000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/DST76Wj/71.jpg'] },
  { sku: 'SC1067#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 67', price: 8000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/21PXkjvJ/72.jpg'] },
  { sku: 'SC1068#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 68', price: 8000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/rf4CZg3j/73.jpg'] },
  { sku: 'SC1069#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 69', price: 18000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/XkbX52tT/74.jpg'] },
  { sku: 'SC1070#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 70', price: 8000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/2043pchB/75.jpg'] },
  { sku: 'SC1071#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 71', price: 8000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/YFSr6Vry/76.jpg'] },
  { sku: 'SC1072#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 72', price: 8000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/mCSgkB58/77.jpg'] },
  { sku: 'SC1073#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 73', price: 8000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/FbGYKDx4/78.jpg'] },
  { sku: 'SC1074#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 74', price: 6000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/gZZjg3L0/79.jpg'] },
  { sku: 'SC1075#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 75', price: 18000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: 'NEW', images: ['https://i.ibb.co/h1V42Bg0/80.jpg'] },
  { sku: 'SC1076#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 76', price: 6000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/bRL8Sdvm/81.jpg'] },
  { sku: 'SC1077#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 77', price: 7000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/R4M9P4mZ/82.jpg'] },
  { sku: 'SC1078#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 78', price: 7000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/RpsCR6GZ/83.jpg'] },
  { sku: 'SC1079#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 79', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/gZ4R03ng/84.jpg'] },
  { sku: 'SC1080#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 80', price: 7000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/bM1f0Fz1/85.jpg'] },
  { sku: 'SC1081#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 81', price: 7000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/Hf67qBwF/86.jpg'] },
  { sku: 'SC1082#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 82', price: 7000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/WvQRzKzq/87.jpg'] },
  { sku: 'SC1083#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 83', price: 7000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/v4nQ5yBF/88.jpg'] },
  { sku: 'SC1084#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 84', price: 8000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/tp0NWBkh/89.jpg'] },
  { sku: 'SC1085#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 85', price: 8000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/s90YcPLh/90.jpg'] },
  { sku: 'SC1086#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 86', price: 8000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/20CwKLS8/91.jpg'] },
  { sku: 'SC1087#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 87', price: 8000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/Pvk5F8mJ/92.jpg'] },
  { sku: 'SC1088#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 88', price: 7000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/QFP44D3K/93.jpg'] },
  { sku: 'SC1089#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 89', price: 8000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/sp4gncGG/94.jpg'] },
  { sku: 'SC1090#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 90', price: 10000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: 'NEW', images: ['https://i.ibb.co/0jSvv2ds/95.jpg'] },
  { sku: 'SC1091#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 91', price: 10000, sizes: ['M', 'L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/WpxPh0RT/96.jpg'] },
  { sku: 'SC1092#', brand: 'Under Armour', category: ['sets', 'ua'], name: 'Premium Under Armour Selection - Style 92', price: 10000, sizes: ['S', 'M', 'L', 'XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '🩱', badge: null, images: ['https://i.ibb.co/whKMdFSc/97.jpg'] },
  { sku: 'SC1093#', brand: 'Nike', category: ['tops', 'nike'], name: 'Premium Nike Selection - Style 93', price: 10000, sizes: ['M', 'L', 'XL', '2XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👕', badge: null, images: ['https://i.ibb.co/HD1m10jk/98.jpg'] },
  { sku: 'SC1094#', brand: 'Adidas', category: ['pants', 'adidas'], name: 'Premium Adidas Selection - Style 94', price: 8000, sizes: ['L', 'XL', '2XL', '3XL'], colors: ['#111', '#888', '#fff'], fabric: 'Performance Fabric', desc: 'Collection Premium Sportswear Soft&Cozy. Respirabilité maximale et confort optimal pour vos entraînements à Lomé.', icon: '👖', badge: null, images: ['https://i.ibb.co/G4V2t6dL/99.jpg'] },
];

async function seed() {
  console.log(`${products.length} produits à insérer...`);

  // Créer la table si elle n'existe pas encore
  await pool.query(`
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      sku TEXT,
      brand TEXT,
      category JSONB DEFAULT '[]',
      name TEXT NOT NULL,
      price INTEGER DEFAULT 0,
      sizes JSONB DEFAULT '[]',
      colors JSONB DEFAULT '[]',
      fabric TEXT,
      description TEXT,
      icon TEXT DEFAULT '👕',
      badge TEXT,
      images JSONB DEFAULT '[]',
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
  `);
  console.log('Table products prête.');

  const { rows: existing } = await pool.query('SELECT COUNT(*) FROM products');
  if (parseInt(existing[0].count) > 0) {
    console.log(`La table contient déjà ${existing[0].count} produits. Seed annulé.`);
    console.log("Pour ré-exécuter : videz d'abord la table avec DELETE FROM products;");
    await pool.end();
    return;
  }

  let inserted = 0;
  for (const p of products) {
    await pool.query(
      `INSERT INTO products (sku, brand, category, name, price, sizes, colors, fabric, description, icon, badge, images)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
      [
        p.sku || null,
        p.brand || null,
        JSON.stringify(p.category || []),
        p.name,
        p.price || 0,
        JSON.stringify(p.sizes || []),
        JSON.stringify(p.colors || []),
        p.fabric || null,
        p.desc || null,
        p.icon || '👕',
        p.badge || null,
        JSON.stringify(p.images || []),
      ]
    );
    inserted++;
    process.stdout.write(`\r${inserted}/${products.length} produits insérés...`);
  }

  console.log(`\n✓ ${inserted} produits migrés avec succès dans Supabase !`);
  await pool.end();
}

seed().catch((err) => {
  console.error('Erreur seed :', err.message);
  process.exit(1);
});
